# This file describes your repository contents.
# It should return a set of nix derivations
# and optionally the special attributes `lib`, `modules` and `overlays`.
# It should NOT import <nixpkgs>. Instead, you should take pkgs as an argument.
# Having pkgs default to <nixpkgs> is fine though, and it lets you use short
# commands such as:
#     nix-build -A mypackage

{ pkgs ? import <nixpkgs> { } }:

let
  myLib = import ./lib { inherit pkgs; };
in
{
  # The `lib`, `modules`, and `overlays` names are special
  lib = myLib; # functions
  modules = import ./modules; # NixOS modules
  overlays = import ./overlays; # nixpkgs overlays

  apprun-dedicated-application-provisioner = import ./pkgs/apprun-dedicated-application-provisioner {
    inherit (pkgs) lib;
    inherit (myLib) mkGitHubReleaseBinary;
  };

  db-schema-sync = import ./pkgs/db-schema-sync {
    inherit (pkgs) lib;
    inherit (myLib) mkGitHubReleaseBinary;
  };

  # Generated by goreleaser
  apprun-dedicated-provisioner = pkgs.callPackage ./pkgs/apprun-dedicated-provisioner { };
}
