# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "0rbhlliya0s2hbhrj36c7jkzc4fxmb376vsfa7s6qriidksfy4z6";
    aarch64-linux = "1h82cwsvhdcznv33ygwwhf9s1hc7zqnawk68ayqkzlshwi8hnf64";
    x86_64-darwin = "0x5i6q0mmqdh7ljnhs6pdx3khdz98gywyvasgm7dszm2qflcy3s4";
    aarch64-darwin = "048dm445xhhjjkq64w00rwixv7kwihwdw1ibz0l1zy43a4mvv6v1";
  };

  urlMap = {
    x86_64-linux = "https://github.com/tokuhirom/dashyard/releases/download/v0.19.0/dashyard_0.19.0_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/tokuhirom/dashyard/releases/download/v0.19.0/dashyard_0.19.0_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/tokuhirom/dashyard/releases/download/v0.19.0/dashyard_0.19.0_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/tokuhirom/dashyard/releases/download/v0.19.0/dashyard_0.19.0_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "dashyard";
  version = "0.19.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./dashyard $out/bin/dashyard
  '';

  meta = {
    description = "Lightweight Prometheus metrics dashboard";
    homepage = "https://github.com/tokuhirom/dashyard";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
