# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "00frwmlnvk2zjq5pj9m8bip9qx8xigxqavjffm9lvxn5xq5vcgfv";
    aarch64-linux = "0iwqnzya4h3a7c4nq6fzj99fwgca9rhh5fs869vpijgrm6xrk91s";
    x86_64-darwin = "00pchmd3jjcipakhia1jihxchnld50fja8b5ff6gx0mavpq8ivaj";
    aarch64-darwin = "01dad2pdvnrcyyv5zhgc3zqr2syixmq63aybndi8g700grsjnwc0";
  };

  urlMap = {
    x86_64-linux = "https://github.com/tokuhirom/dashyard/releases/download/v0.16.1/dashyard_0.16.1_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/tokuhirom/dashyard/releases/download/v0.16.1/dashyard_0.16.1_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/tokuhirom/dashyard/releases/download/v0.16.1/dashyard_0.16.1_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/tokuhirom/dashyard/releases/download/v0.16.1/dashyard_0.16.1_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "dashyard";
  version = "0.16.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./dashyard $out/bin/dashyard
  '';

  meta = {
    description = "Lightweight Prometheus metrics dashboard";
    homepage = "https://github.com/tokuhirom/dashyard";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
