# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "1zkv1pd5zjhmilrw23kz9i4xfjlh1dcgw2k9192fs17pl9d9vpp9";
    aarch64-linux = "07xy9v2fmpc632is2df0j35xi5vcshvzi8sg7mwdb74xpyb5vpjd";
    x86_64-darwin = "01dfr6bgxmg9zvipxjj4firjp7fzb6sxjxy80mq0v10jicjlnwkh";
    aarch64-darwin = "1ybs57v7qlfmcyiwqk65s109v237zb9kr33hnk1jja8l6c4dqqrc";
  };

  urlMap = {
    x86_64-linux = "https://github.com/tokuhirom/dashyard/releases/download/v0.6.1/dashyard_0.6.1_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/tokuhirom/dashyard/releases/download/v0.6.1/dashyard_0.6.1_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/tokuhirom/dashyard/releases/download/v0.6.1/dashyard_0.6.1_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/tokuhirom/dashyard/releases/download/v0.6.1/dashyard_0.6.1_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "dashyard";
  version = "0.6.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./dashyard $out/bin/dashyard
  '';

  meta = {
    description = "Lightweight Prometheus metrics dashboard";
    homepage = "https://github.com/tokuhirom/dashyard";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
