# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
  lib,
  fetchurl,
  installShellFiles,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  shaMap = {
    x86_64-linux = "05fj38407ydzil5dx7ghknqlw1ghg06qhjf3m2wrg8gfdrp4jicy";
    aarch64-linux = "1wa7rdyaz5ycxhmg852hmixrajszhmsji7x2g8nbcnv0p7dhrirl";
    x86_64-darwin = "1ddrc14x5a0nl47sih80vdpbckgrjir27zsc57y3y5rv0gpm3ddg";
    aarch64-darwin = "0nh5drrmb1ymg149iq9c7xnvc0xxj57bjlnbsc3z9a036zm69p70";
  };

  urlMap = {
    x86_64-linux = "https://github.com/tokuhirom/apprun-dedicated-provisioner/releases/download/v0.1.1/apprun-dedicated-provisioner_0.1.1_linux_amd64.tar.gz";
    aarch64-linux = "https://github.com/tokuhirom/apprun-dedicated-provisioner/releases/download/v0.1.1/apprun-dedicated-provisioner_0.1.1_linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/tokuhirom/apprun-dedicated-provisioner/releases/download/v0.1.1/apprun-dedicated-provisioner_0.1.1_darwin_amd64.tar.gz";
    aarch64-darwin = "https://github.com/tokuhirom/apprun-dedicated-provisioner/releases/download/v0.1.1/apprun-dedicated-provisioner_0.1.1_darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "apprun-dedicated-provisioner";
  version = "0.1.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./apprun-dedicated-provisioner $out/bin/apprun-dedicated-provisioner
  '';

  meta = {
    description = "CLI tool for managing Sakura Cloud AppRun Dedicated application provisioning";
    homepage = "https://github.com/tokuhirom/apprun-dedicated-provisioner";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
